### ISSUE TITLE
Advice for dealing with barcode multiplexing

### ISSUE THREAD

**Issue by peterdfields** [google/deepconsensus#32]
Hi,

I'd like to use deepconsensus on a set of HiFi datasets that were generated on a Sequel II but with barcoded multiplexing. My understanding is that without running the CCS step first detecting barcodes can be difficult. Do you have a recommended pipeline for going from a barcoded subread bam file in order to generate the subset of necessary inputs for CCS/actc/deepconsensus? Thank you for your time and advice.

**Comment by kishwarshafin** [comment]
Hi @peterdfields ,

Given the fact that the de-multiplexing algorithm is designed to work with CCS reads and currently we don't have any benchmarking available to provide you more context if there would be any contamination introduced due to the use of DeepConsensus, our recommendation would be to first de-multiplex the CCS reads with Lima and then apply DeepConsensus to the de-multiplexed reads independently.

**Comment by armintoepfer** [comment]
Linking the duplicate: https://github.com/PacificBiosciences/pbbioconda/issues/523

**Comment by peterdfields** [comment]
Thank you @armintoepfer
