### ISSUE TITLE
bam or fastq issue

### ISSUE THREAD

**Issue by HITzhongyu** [google/deepconsensus#67]
Hi，
      
I am tryting to use the output of deepconsensus, either in fastq or bam format, for downstream methylation detection. However, I noticed that the processed data by deepconsensus does not retain the IPW and PW tags, which are essential for methylation detection. I want to inquire if deepconsensus has any functionality to match the processed fastq or bam data with the original CCS data, in order to accommodate downstream methylation detection.

**Comment by danielecook** [comment]
Hi @HITzhongyu, DeepConsensus tends to removes bases to improve accuracy. In order to carry the IP/PW values forward we would have to remove the corresponding bases from the IP/PW arrays. This would require an additional alignment step to identify deleted positions and remove them.

Unfortunately, at this time, this is not a use case we are able to support.

**Comment by HITzhongyu** [comment]
@danielecook ok thanks！
